module.exports = {
  tutorialSidebar: [
    'intro',

    {
      type: 'autogenerated',
      dirName: 'tutorial-basics',
    },

    {
      type: 'autogenerated',
      dirName: 'tutorial-extras',
    },

    {
      type: 'autogenerated',
      dirName: 'api',
    },

    {
      type: 'autogenerated',
      dirName: 'graphql',
    },
  ],
};